FROM hexpm/elixir:1.16.3-erlang-26.2.5.2-alpine

RUN apk add --no-cache build-base git inotify-tools postgresql-client

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

ENV MIX_ENV=dev

EXPOSE 4000

CMD ["mix", "phx.server"]
